# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8122b3279f2587e362c34f1b20df5008c7211c10c666774a8296dacf2b94fd6397ae2635df42e625e9bed931af7e7364c2ed007c923a29ce1c235a167a5d368

test:
  secret_key_base: 30051c903e7405c65a18088b67ffa917ae856e61c6b852b179d4c274ad00821aaf04a1df2b59199afa28fb9e54a617237cb280f66eb3035c73c0551d1e9c2ac8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
